project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/prateekshukla1108
format:
  html:
    theme: darkly
    css: styles.css
execute:
  freeze: auto


